using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Preferences;
using Content.Shared.Vanilla.Skill;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Content.Shared.Vanilla.RoleSkills;
using Content.Client.UserInterface.Systems.Character.Basicskills;
using Content.Client.UserInterface.Systems.Character.Easyskills;

namespace Content.Client.Vanilla.UserInterface.Lobby.RoleSkillsUI;

[GenerateTypedNameReferences]
public sealed partial class RoleSkillsWindow : FancyWindow
{
    [Dependency] private IEntitySystemManager _sysMan = default!;
    private readonly SharedSkillSystem? _skill;

    public event Action<RoleSkills>? OnSavePressed;
    private RoleSkills _currentRoleSkills;
    private RoleSkillsPrototype _proto;
    public HumanoidCharacterProfile Profile;
    bool firstjoin = true;
    public RoleSkillsWindow(
        HumanoidCharacterProfile profile,
        RoleSkills roleSkills,
        RoleSkillsPrototype proto,
        IDependencyCollection collection)
    {
        RobustXamlLoader.Load(this);
        Profile = profile;
        _proto = proto;
        _currentRoleSkills = roleSkills.Clone();
        _skill ??= _sysMan.GetEntitySystem<SharedSkillSystem>();

        RefreshInformation();
        ButtonSave.OnPressed += _ => OnSave();
        ButtonReset.OnPressed += _ => OnReset();
    }

    private void OnSave()
    {
        firstjoin = true;
        OnSavePressed?.Invoke(_currentRoleSkills);
        RefreshInformation();
    }

    private void OnReset()
    {
        _currentRoleSkills.AddedBasicSkills = new();
        _currentRoleSkills.AddedEasySkills = new();
        RefreshInformation();
    }

    private void RefreshInformation()
    {
        BasicSkillContainer.Children.Clear();
        EasySkillContainer.Children.Clear();
        Skillpoints.Visible = false;
        //навыки
        int skillpoints = _proto.SkillPoints;
        List<(SkillType Skill, SkillLevel Level, int Experience)> basicSkills = [];
        List<(SkillType Skill, bool have, int Experience)> easySkills = [];
        foreach (var skill in Enum.GetValues<SkillType>())
        {
            switch (skill.GetKind())
            {
                case SkillKind.Basic:
                    basicSkills.Add((skill, SkillLevel.None, 0));
                    break;

                case SkillKind.Easy:
                    easySkills.Add((skill, false, 0));
                    break;
            }
        }

        void ApplyBasicSkills(Dictionary<SkillType, SkillLevel>? Skills)
        {
            if (Skills == null)
                return;

            foreach (var (skill, level) in Skills)
            {
                int index = basicSkills.FindIndex(s => s.Skill == skill);
                if (index == -1)
                    continue;

                var current = basicSkills[index];
                int currentLevel = (int)current.Level;
                int addedLevel = (int)level;
                int total = currentLevel + addedLevel;

                SkillLevel newLevel = total > (int)SkillLevel.Expert
                    ? SkillLevel.Expert
                    : (SkillLevel)total;

                int finalLevel = (int)newLevel;

                // Вернём излишек, если превышен максимум
                if (total > (int)SkillLevel.Expert)
                    skillpoints += total - (int)SkillLevel.Expert;

                // Списываем только разницу между новым и текущим уровнями
                int delta = finalLevel - currentLevel;
                skillpoints -= delta;

                basicSkills[index] = (skill, newLevel, 0);
            }
        }

        void ApplyEasySkills(HashSet<SkillType>? Skills)
        {
            if (Skills == null)
                return;

            foreach (var skill in Skills)
            {
                int index = easySkills.FindIndex(s => s.Skill == skill);
                if (index == -1)
                    continue;

                var current = easySkills[index];
                if (current.have)
                {
                    skillpoints += 1;
                }
                else
                {
                    skillpoints -= 1;
                    easySkills[index] = (skill, true, 0);
                }
            }
        }
        // Собираем в кучу обязательные навыки роли и выбор игрока
        ApplyBasicSkills(_currentRoleSkills.AddedBasicSkills);
        ApplyEasySkills(_currentRoleSkills.AddedEasySkills);
        ApplyEasySkills(_proto.EasySkills);
        ApplyBasicSkills(_proto.BasicSkills);

        //Основные навыки
        foreach (var (skillName, level, experience) in basicSkills)
        {
            bool canBeModified = skillpoints > 0;
            var skillControl = new SkillControl(skillName, level, experience, canBeModified);
            skillControl.OnPressed += () => AddSkill(skillName);

            BasicSkillContainer.Children.Add(skillControl);
        }
        //Лёгкие навыки
        foreach (var (skillName, have, experience) in easySkills)
        {
            var easyskillsControl = new EasyskillsControl(skillName, have, experience, skillpoints > 0);
            easyskillsControl.OnPressed += () => AddSkill(skillName);

            EasySkillContainer.Children.Add(easyskillsControl);
        }
        //Скиллпоинты
        if (skillpoints > 0)
        {
            var skillpointMessage = new FormattedMessage();
            skillpointMessage.AddMarkupOrThrow(Loc.GetString("rolebackground-ui-SkillPoints", ("count", skillpoints)));
            Skillpoints.SetMessage(skillpointMessage);
            Skillpoints.Visible = true;
        }

        ButtonSave.Disabled = skillpoints != 0 || firstjoin;
        firstjoin = false;
    }

    private void AddSkill(SkillType skillName)
    {
        switch (skillName.GetKind())
        {
            case SkillKind.Basic:
                if (_currentRoleSkills.AddedBasicSkills.TryGetValue(skillName, out var currentLevel))
                {
                    if ((int)currentLevel < (int)SkillLevel.Expert)
                        _currentRoleSkills.AddedBasicSkills[skillName] = currentLevel + 1;
                }
                else
                {
                    _currentRoleSkills.AddedBasicSkills[skillName] = SkillLevel.Basic;
                }
                break;

            case SkillKind.Easy:
                if (!_currentRoleSkills.AddedEasySkills.Contains(skillName))
                {
                    _currentRoleSkills.AddedEasySkills.Add(skillName);
                }
                break;
        }
        RefreshInformation();
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.None;
    }
}
