using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Dataset;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Random.Helpers;
using Content.Shared.Vanilla.Skill;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Robust.Client.UserInterface.Controls;
using Content.Shared.Vanilla.RoleSkills;
using Content.Client.UserInterface.Systems.Character.Basicskills;
using Content.Client.UserInterface.Systems.Character.Easyskills;
using Robust.Client.UserInterface.CustomControls;
using System.Linq;

namespace Content.Client.Vanilla.UserInterface.Lobby.RoleSkillsUI;

[GenerateTypedNameReferences]
public sealed partial class RoleSkillsWindow : FancyWindow
{
    public event Action<RoleSkills>? OnSavePressed;
    private RoleSkills CurrentRoleSkills;
    private RoleSkillsPrototype _proto;
    public HumanoidCharacterProfile Profile;
    bool firstjoin = true;
    public RoleSkillsWindow(
        HumanoidCharacterProfile profile,
        RoleSkills roleSkills,
        RoleSkillsPrototype proto,
        IDependencyCollection collection)
    {
        RobustXamlLoader.Load(this);
        Profile = profile;
        _proto = proto;
        CurrentRoleSkills = roleSkills.Clone();

        RefreshInformation(collection);
        ButtonSave.OnPressed += _ => OnSave(collection);
        ButtonReset.OnPressed += _ => OnReset(collection);

    }
    private void OnSave(IDependencyCollection collection)
    {
        firstjoin = true;
        OnSavePressed?.Invoke(CurrentRoleSkills);
        RefreshInformation(collection);
    }
    private void OnReset(IDependencyCollection collection)
    {
        CurrentRoleSkills.AddedBasicSkills = new();
        CurrentRoleSkills.AddedEasySkills = new();
        RefreshInformation(collection);
    }

    private void RefreshInformation(IDependencyCollection collection)
    {
        BasicSkillContainer.Children.Clear();
        EasySkillContainer.Children.Clear();
        Skillpoints.Visible = false;
        int skillpoints = 12;//ХАРДКОДЕТ

        //навыки
        List<(skillType Skill, SkillLevel Level, int Experience)> generalbasicskills = new List<(skillType Skill, SkillLevel Level, int Experience)>
        {
            (skillType.RangeWeapon, SkillLevel.None, 0),
            (skillType.MeleeWeapon, SkillLevel.None, 0),
            (skillType.Medicine, SkillLevel.None, 0),
            (skillType.Chemistry, SkillLevel.None, 0),
            (skillType.Engineering, SkillLevel.None, 0),
            (skillType.Building, SkillLevel.None, 0),
            (skillType.Research, SkillLevel.None, 0),
            (skillType.Crime, SkillLevel.None, 0)
        };
        List<(skillType Skill, bool have, int Experience)> generaleasyskills = new List<(skillType Skill, bool have, int Experience)>
        {
            (skillType.Piloting, false, 0),
            (skillType.Botany, false, 0),
            (skillType.MusInstruments, false, 0),
            (skillType.Bureaucracy, false, 0),
            (skillType.Atmosphere, false, 0)
        };

        void ApplyBasicSkills(Dictionary<skillType, SkillLevel>? Skills)
        {
            if (Skills == null)
                return;

            foreach (var (skill, level) in Skills)
            {
                int index = generalbasicskills.FindIndex(s => s.Skill == skill);
                if (index == -1)
                    continue;

                var current = generalbasicskills[index];
                int total = (int)current.Level + (int)level;
                SkillLevel newLevel = total > (int)SkillLevel.Expert
                    ? SkillLevel.Expert
                    : (SkillLevel)total;

                if (total > (int)SkillLevel.Expert)
                    skillpoints += total - (int)SkillLevel.Expert;

                skillpoints -= (int)newLevel;
                generalbasicskills[index] = (skill, newLevel, 0);
            }
        }

        void ApplyEasySkills(HashSet<skillType>? Skills)
        {
            if (Skills == null)
                return;

            foreach (var skill in Skills)
            {
                int index = generaleasyskills.FindIndex(s => s.Skill == skill);
                if (index == -1)
                    continue;

                var current = generaleasyskills[index];
                if (current.have)
                {
                    skillpoints += 1;
                }
                else
                {
                    skillpoints -= 1;
                    generaleasyskills[index] = (skill, true, 0);
                }
            }
        }

        // Собираем в кучу обязательные навыки роли и выбор игрока
        ApplyBasicSkills(CurrentRoleSkills.AddedBasicSkills);
        ApplyEasySkills(CurrentRoleSkills.AddedEasySkills);
        ApplyEasySkills(_proto.EasySkills);
        ApplyBasicSkills(_proto.BasicSkills);

        //Основные навыки
        foreach (var (skillName, level, experience) in generalbasicskills)
        {
            var skillControl = new SkillControl(skillName, level, experience, skillpoints > 0);
            skillControl.OnPressed += () => AddSkill(skillName, collection);

            BasicSkillContainer.Children.Add(skillControl);
        }
        //Лёгкие навыки
        foreach (var (skillName, have, experience) in generaleasyskills)
        {
            var easyskillsControl = new EasyskillsControl(skillName, have, experience, skillpoints > 0 );
            easyskillsControl.OnPressed += () => AddSkill(skillName, collection);

            EasySkillContainer.Children.Add(easyskillsControl);
        }
        //Скиллпоинты
        if (skillpoints>0)
        {
            var skillpointMessage = new FormattedMessage();
            skillpointMessage.AddMarkupOrThrow(Loc.GetString("rolebackground-ui-SkillPoints", ("count", skillpoints) ));
            Skillpoints.SetMessage(skillpointMessage);
            Skillpoints.Visible = true;
        }

        ButtonSave.Disabled = skillpoints != 0 || firstjoin;
        firstjoin = false;
    }

    private void AddSkill(skillType skillName, IDependencyCollection collection)
    {
        if (SkillComponent.IsEasySkill(skillName))
        {
            if (!CurrentRoleSkills.AddedEasySkills.Contains(skillName))
            {
                CurrentRoleSkills.AddedEasySkills.Add(skillName);
                RefreshInformation(collection);
            }
            return;
        }

        if (CurrentRoleSkills.AddedBasicSkills.TryGetValue(skillName, out var currentLevel))
        {
            if ((int)currentLevel < (int)SkillLevel.Expert)
                CurrentRoleSkills.AddedBasicSkills[skillName] = currentLevel + 1;
        }
        else
        {
            CurrentRoleSkills.AddedBasicSkills[skillName] = SkillLevel.Basic;
        }

        RefreshInformation(collection);
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.None;
    }
}
