using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Client.ResourceManagement;
using Content.Shared.Vanilla.Skill;

namespace Content.Client.UserInterface.Systems.Character.Basicskills;

[GenerateTypedNameReferences]
public sealed partial class SkillControl : Control
{
    public Action? OnPressed;
    private int _exp=0;
    private int _lvl=0;
    private Color _colorlvl = Color.FromHex("#8F969B");
 
    public SkillControl(skillType SkillName, SkillLevel Level, int Experience, bool haveskillpoint)
    {
        RobustXamlLoader.Load(this);
        var resCache = IoCManager.Resolve<IResourceCache>();
        var iconlvl = resCache.GetResource<TextureResource>("/Textures/Vanilla/Interface/SkillLvlIcons/lvl0.png");
        _exp = Experience;
        _lvl = (int)Level;

        switch (_lvl)
        {
            case 0:
                break;

            case 1:
                iconlvl = resCache.GetResource<TextureResource>("/Textures/Vanilla/Interface/SkillLvlIcons/lvl1.png");
                _colorlvl = Color.FromHex("#629EFF");
                break;

            case 2:
                iconlvl = resCache.GetResource<TextureResource>("/Textures/Vanilla/Interface/SkillLvlIcons/lvl2.png");
                _colorlvl = Color.FromHex("#FF9821");
                break;

            case 3:
                iconlvl = resCache.GetResource<TextureResource>("/Textures/Vanilla/Interface/SkillLvlIcons/lvl3.png");
                _colorlvl = Color.FromHex("#9769FF");
                break;
        }

        Background.ModulateSelfOverride = _colorlvl;
        SkillTexture.Texture = iconlvl;

        var skillnamemessage = new FormattedMessage();
        skillnamemessage.AddMarkupOrThrow(Loc.GetString("skill-system-UI-SkillNameLabel", ("skillname", SkillName.ToString())));

        var Lvlmessage = new FormattedMessage();
        Lvlmessage.AddMarkupOrThrow(Loc.GetString( "skill-system-UI-Lvllabel", ("lvl", _lvl), ("color", _colorlvl), ("amnesia", "") ) );

        var Expmessage = new FormattedMessage();
        if(_lvl < 3)
            Expmessage.AddMarkupOrThrow(Loc.GetString( "skill-system-UI-ExpLabel", ("exp", _exp), ("amnesia", "") ));
        else
            Expmessage.AddMarkupOrThrow(Loc.GetString("skill-system-UI-ExpLabel-maxlvl"));

        SkillNameLabel.SetMessage(skillnamemessage);
        LvlLabel.SetMessage(Lvlmessage);
        ExpLabel.SetMessage(Expmessage);

        MainButton.OnPressed += _ => OnPressed?.Invoke();
        MainButton.Disabled = !haveskillpoint || _lvl == 3 ;
        MainButton.ToolTip = Loc.GetString($"skill-system-UI-Tooltip-{SkillName.ToString()}");
        
    }
    public void updateamnesia(skillType skill, int exptorestore)
    {
        var Lvlmessage = new FormattedMessage();
        var Expmessage = new FormattedMessage();

        Lvlmessage.AddMarkupOrThrow(Loc.GetString( "skill-system-UI-Lvllabel", ("lvl", _lvl), ("color", _colorlvl), ("amnesia", "(амнезия)") ) );
        LvlLabel.SetMessage(Lvlmessage);

        string restoreexp = $", ({exptorestore})";
        Expmessage.AddMarkupOrThrow(Loc.GetString( "skill-system-UI-ExpLabel", ("exp", _exp), ("amnesia", restoreexp) ));
        ExpLabel.SetMessage(Expmessage);

    }
}