using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Client.UserInterface.Controls;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Content.Client.Vanilla.AlertKey
{
    [GenerateTypedNameReferences]
    public sealed partial class AlertKeyMenu : FancyWindow
    {
        public bool AlertLevelSelectable;
        public event Action<string, HashSet<string>, HashSet<string>>? OnApply;
        public List<(string Level, bool IsSubcode, bool blocked)>? Alerts;
        private HashSet<string> subcodestoadd = new();
        private HashSet<string> subcodestorem = new();
        private string? _selectedMainLevel;

        public AlertKeyMenu()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            ApplyButton.Disabled = !AlertLevelSelectable;


            MainSelection.OnItemSelected += args =>
            {
                _selectedMainLevel = MainSelection.GetItemMetadata(args.Id) as string;
                UpdateMainSelection(_selectedMainLevel);
                InfoLabel.SetMessage(Loc.GetString($"alertkey-level-reasons-{_selectedMainLevel}"));
            };

            ApplyButton.OnPressed += _ =>
            {
                var mainCode = _selectedMainLevel ?? string.Empty;

                // Вызываем событие OnApply
                OnApply?.Invoke(mainCode, subcodestoadd, subcodestorem);
            };

        }

        // Получаем список кодов, для которых кнопки нажаты
        private List<string> GetPressedSubCodes()
        {
            var additionalCodes = new List<string>();
            foreach (var child in SubLevelContainer.Children)
            {
                if (child is Button btn && btn.Pressed && !string.IsNullOrEmpty(btn.Name))
                {
                    additionalCodes.Add(btn.Name);
                }
            }
            return additionalCodes;
        }

        // Обработчик для переключения состояния подуровней
        private void OnSubLevelToggled(string level, bool isPressed)
        {
            if (isPressed)
            {
                subcodestoadd.Add(level);
                subcodestorem.Remove(level);
                InfoLabel.SetMessage(Loc.GetString($"alertkey-level-reasons-{level}"));
            }
            else
            {
                subcodestorem.Add(level);
                subcodestoadd.Remove(level);
            }
        }

        public void UpdateAlertLevels(List<(string Level, bool IsSubcode, bool blocked)>? alerts, string currentAlert, HashSet<string> ActiveSubLevels)
        {
            MainSelection.Clear();
            SubLevelContainer.RemoveAllChildren();
            _selectedMainLevel = currentAlert;
            if (alerts == null)
            {
                // Если список пуст, добавляем только текущий основной код
                AddMainLevel(currentAlert);
            }
            else
            {
                // Проходим по всем уровням
                foreach (var (level, IsSubcode, blocked) in alerts)
                {
                    if (IsSubcode)
                        CreateSubLevelButton(level, ActiveSubLevels.Contains(level), blocked);
                    else
                        AddMainLevel(level, currentAlert);
                }
            }
        }
        private void UpdateMainSelection(string? selectedLevel)
        {
            // Очищаем текущие элементы
            MainSelection.Clear();

            // Перезаполняем выпадающий список с новыми уровнями
            if (Alerts != null)
            {
                foreach (var (level, isSubcode, _) in Alerts)
                {
                    if (!isSubcode)  // Добавляем только основные уровни
                    {
                        AddMainLevel(level, selectedLevel);
                    }
                }
            }
        }

        // Добавляем основной уровень угроз
        private void AddMainLevel(string level, string? selectedLevel = null)
        {
            if (Alerts == null)
                return;

            var alert = Alerts.FirstOrDefault(a => a.Level == level);
            if (alert == default)
                return;

            var name = Loc.GetString($"alert-level-{level}");
            MainSelection.AddItem(name);
            int index = MainSelection.ItemCount - 1; // Получаем индекс последнего добавленного элемента

            MainSelection.SetItemMetadata(index, level);

            // Если уровень заблокирован — делаем его неактивным
            if (alert.blocked)
            {
                MainSelection.SetItemDisabled(index, true);
            }
            else if (level == selectedLevel)
            {
                MainSelection.Select(index);
            }
        }





        // Создаем кнопку для подуровня
        private void CreateSubLevelButton(string level, bool isPressed, bool isblocked)
        {
            var button = new Button
            {
                Text = Loc.GetString($"alert-level-{level}"),
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = isPressed,
                Name = level,
                Disabled = (isblocked || !AlertLevelSelectable)
            };
            if(!isblocked) button.OnPressed += _ => OnSubLevelToggled(level, button.Pressed);
            SubLevelContainer.AddChild(button);
        }
    }
}
