using System.Linq;
using Content.Corvax.Interfaces.Shared;
using Content.Shared.Clothing;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Content.Client.Vanilla.Background;
using Content.Shared.Vanilla.Background;
using Content.Client.Vanilla.UserInterface.Background;

namespace Content.Client.Vanilla.UserInterface.Lobby.BackgroundUI;

[GenerateTypedNameReferences]
public sealed partial class BackgroundGroupContainer : BoxContainer
{
    private readonly BackgroundGroupPrototype _groupProto;
    public event Action<ProtoId<BackgroundPrototype>, ProtoId<BackgroundGroupPrototype>>? OnBackgroundSelected;

    [Dependency] private readonly ILogManager _logMan = default!;
    private ISawmill _sawmill = default!;

    public BackgroundGroupContainer(HumanoidCharacterProfile profile, BackGround? background, BackgroundGroupPrototype groupProto, ICommonSession session, IDependencyCollection collection)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _groupProto = groupProto;
        _sawmill = _logMan.GetSawmill("ПРЕДЫСТОРИИ.BackgroundGroupContainer");
        RefreshBackgrounds(profile, background, session, collection);
    }

    /// <summary>
    /// Updates button availabilities and buttons.
    /// </summary>
    public void RefreshBackgrounds(HumanoidCharacterProfile profile, BackGround? background, ICommonSession session, IDependencyCollection collection)
    {
        var protoMan = collection.Resolve<IPrototypeManager>();
        var backgroundSystem = collection.Resolve<IEntityManager>().System<SharedBackgroundSystem>();

        BackgroundsContainer.DisposeAllChildren();
        var groupbackgrounds = _groupProto.Backgrounds;

        foreach (var bgId in groupbackgrounds)
        {
            if (!protoMan.TryIndex(bgId, out var bgProto))
            {
                _sawmill.Error($"Не найдена предыстория: {bgId}");
                continue;
            }

            var control = new BackgroundControl(
                bgProto.Name,
                bgProto.Description,
                bgProto.SpecialDesc,
                bgProto.Skills,
                bgProto.EasySkills,
                bgProto.SkillPoints
            );

            control.OnPressed += () => OnBackgroundSelected?.Invoke(bgId, _groupProto.ID);
            BackgroundsContainer.AddChild(control);
        }


    }
}