using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Dataset;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Random.Helpers;
using Content.Shared.Vanilla.Skill;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Robust.Client.UserInterface.Controls;
using Content.Client.Vanilla.Background;
using Content.Shared.Vanilla.Background;
using Content.Client.UserInterface.Systems.Character.Basicskills;
using Content.Client.UserInterface.Systems.Character.Easyskills;
using Robust.Client.UserInterface.CustomControls;
using System.Linq;

namespace Content.Client.Vanilla.UserInterface.Lobby.BackgroundUI;

[GenerateTypedNameReferences]
public sealed partial class BackgroundWindow : FancyWindow
{
    public event Action<ProtoId<BackgroundPrototype>, ProtoId<BackgroundGroupPrototype>>? OnBackgroundPressed;

    private BackgroundGroupContainer? _babyGroupContainer;
    private BackgroundGroupContainer? _adultGroupContainer;
    private BackgroundGroupContainer? _generalGroupContainer;


    private ProtoId<BackgroundPrototype>? _selectedBabyBackground;
    private ProtoId<BackgroundPrototype>? _selectedGeneralBackground;
    private ProtoId<BackgroundPrototype>? _selectedAdultBackground;
    private Dictionary<skillType, SkillLevel> addedbasicskills = new();
    private HashSet<skillType> addedeasyskills = new();


    public HumanoidCharacterProfile Profile;
    private int SkillpointCredit = 0;
    public BackgroundWindow(
        HumanoidCharacterProfile profile,
        RoleBackground background,
        RoleBackgroundPrototype proto,
        ICommonSession session,
        IDependencyCollection collection)
    {
        RobustXamlLoader.Load(this);
        Profile = profile;
        var protoManager = collection.Resolve<IPrototypeManager>();
        _selectedBabyBackground = background.SelectedBabyBackground?.Prototype;
        _selectedGeneralBackground = background.SelectedAdultBackground?.Prototype;
        _selectedAdultBackground = background.SelectedGeneralBackground?.Prototype;
        // Baby group
        if (protoManager.TryIndex(proto.Baby, out var babyGroup))
        {
            _babyGroupContainer = new BackgroundGroupContainer(profile, background.SelectedBabyBackground, babyGroup, session, collection);
            LoadoutGroupsContainer.AddTab(_babyGroupContainer, Loc.GetString("детство"));

            _babyGroupContainer.OnBackgroundSelected += (protoId, groupId) =>
            {
                _selectedBabyBackground = protoId;
                _selectedGeneralBackground = null;
                addedeasyskills = new();
                addedbasicskills = new();
                SkillpointCredit = 0;
                RefreshInformation(collection);
            };
        }

        // Adult group
        if (protoManager.TryIndex(proto.Adult, out var adultGroup))
        {
            _adultGroupContainer = new BackgroundGroupContainer(profile, background.SelectedAdultBackground, adultGroup, session, collection);
            LoadoutGroupsContainer.AddTab(_adultGroupContainer, Loc.GetString("зрелость"));

            _adultGroupContainer.OnBackgroundSelected += (protoId, groupId) =>
            {
                _selectedAdultBackground=protoId;
                _selectedGeneralBackground=null;
                addedeasyskills = new();
                addedbasicskills = new();
                SkillpointCredit = 0;
                RefreshInformation(collection);
            };
        }

        // General group
        if (protoManager.TryIndex(proto.General, out var generalGroup))
        {
            _generalGroupContainer = new BackgroundGroupContainer(profile, background.SelectedGeneralBackground, generalGroup, session, collection);
            LoadoutGroupsContainer.AddTab(_generalGroupContainer, Loc.GetString("общее"));

            _generalGroupContainer.OnBackgroundSelected += (protoId, groupId) =>
            {
                _selectedGeneralBackground=protoId;
                _selectedAdultBackground=null;
                _selectedBabyBackground=null;
                addedeasyskills = new();
                addedbasicskills = new();
                SkillpointCredit = 0;
                RefreshInformation(collection);
            };
        }

        // Hide if no groups
        if (_babyGroupContainer == null && _adultGroupContainer == null && _generalGroupContainer == null)
        {
            LoadoutGroupsContainer.Visible = false;
            SetSize = Vector2.Zero;
        }

        RefreshInformation(collection);
        ButtonSave.OnPressed += _ => OnSave();
        ButtonReset.OnPressed += _ => OnReset(collection);
        
    }
    private void OnSave()
    {
        ButtonSave.Disabled = true;
    }
    private void OnReset(IDependencyCollection collection)
    {
        _selectedBabyBackground=null;
        _selectedAdultBackground=null;
        _selectedGeneralBackground=null;
        addedeasyskills = new();
        addedbasicskills = new();
        SkillpointCredit = 0;
        RefreshInformation(collection);
    }
    public void RefreshBackgrounds(RoleBackground background, ICommonSession session, IDependencyCollection collection)
    {
        // Refresh each container if it exists
        if (_babyGroupContainer != null)
            _babyGroupContainer.RefreshBackgrounds(Profile, background.SelectedBabyBackground, session, collection);
        if (_adultGroupContainer != null)
            _adultGroupContainer.RefreshBackgrounds(Profile, background.SelectedAdultBackground, session, collection);
        if (_generalGroupContainer != null)
            _generalGroupContainer.RefreshBackgrounds(Profile, background.SelectedGeneralBackground, session, collection);
    }

    private void RefreshInformation(IDependencyCollection collection)
    {

        ButtonSave.Disabled = false;
        SelectedSpecials.Visible = false;
        Skillpoints.Visible = false;
        Dictionary<skillType, SkillLevel>? BabyBackgroundBasicSkills = null;
        Dictionary<skillType, SkillLevel>? AdultBackgroundBasicSkills = null;
        Dictionary<skillType, SkillLevel>? GeneralBackgroundBasicSkills = null;
        HashSet<skillType>? BabyBackgroundEasySkills = null;
        HashSet<skillType>? AdultBackgroundEasySkills = null;
        HashSet<skillType>? GeneralBackgroundEasySkills = null;

        var protoManager = collection.Resolve<IPrototypeManager>();

        var selectedBackgroundMessage = new FormattedMessage();
        selectedBackgroundMessage.AddMarkupOrThrow(Loc.GetString("rolebackground-ui-selectedbackgrounds-header"));
        selectedBackgroundMessage.PushMarkup("");
        List<string> SpecialDesc = new();

        if (_selectedBabyBackground != null && protoManager.TryIndex(_selectedBabyBackground, out var bgProtoBaby))
        {
            selectedBackgroundMessage.PushMarkup(Loc.GetString("rolebackground-ui-selectedbackgrounds-item", ("name", Loc.GetString(bgProtoBaby.Name))));
            if (bgProtoBaby.SpecialDesc != null)
                SpecialDesc.AddRange(bgProtoBaby.SpecialDesc);
            BabyBackgroundBasicSkills = new(bgProtoBaby.Skills);
            BabyBackgroundEasySkills = new(bgProtoBaby.EasySkills);
        }

        if (_selectedAdultBackground != null && protoManager.TryIndex(_selectedAdultBackground, out var bgProtoAdult))
        {
            selectedBackgroundMessage.PushMarkup(Loc.GetString("rolebackground-ui-selectedbackgrounds-item", ("name", Loc.GetString(bgProtoAdult.Name))));
            if (bgProtoAdult.SpecialDesc != null)
                SpecialDesc.AddRange(bgProtoAdult.SpecialDesc);
            AdultBackgroundBasicSkills = new(bgProtoAdult.Skills);
            AdultBackgroundEasySkills = new(bgProtoAdult.EasySkills);
        }

        if (_selectedGeneralBackground != null && protoManager.TryIndex(_selectedGeneralBackground, out var bgProtoGeneral))
        {
            selectedBackgroundMessage.PushMarkup(Loc.GetString("rolebackground-ui-selectedbackgrounds-item", ("name", Loc.GetString(bgProtoGeneral.Name))));
            if (bgProtoGeneral.SpecialDesc != null)
                SpecialDesc.AddRange(bgProtoGeneral.SpecialDesc);
            GeneralBackgroundBasicSkills = new(bgProtoGeneral.Skills);
            GeneralBackgroundEasySkills = new(bgProtoGeneral.EasySkills);
        }

        SelectedBackgrounds.SetMessage(selectedBackgroundMessage);

        //Особое
        if (SpecialDesc.Count > 0)
        {
            var specialMsg = new FormattedMessage();
            specialMsg.PushMarkup(Loc.GetString("background-ui-specials-header"));
            foreach (var specialText in SpecialDesc)
            {
                specialMsg.PushMarkup(specialText);
            }
            SelectedSpecials.Visible = true;
            SelectedSpecials.SetMessage(specialMsg);
        }
        BasicSkillContainer.Children.Clear();
        EasySkillContainer.Children.Clear();

        //навыки
        List<(skillType Skill, SkillLevel Level, int Experience)> generalbasicskills = new List<(skillType Skill, SkillLevel Level, int Experience)>
        {
            (skillType.RangeWeapon, SkillLevel.None, 0),
            (skillType.MeleeWeapon, SkillLevel.None, 0),
            (skillType.Medicine, SkillLevel.None, 0),
            (skillType.Chemistry, SkillLevel.None, 0),
            (skillType.Engineering, SkillLevel.None, 0),
            (skillType.Building, SkillLevel.None, 0),
            (skillType.Research, SkillLevel.None, 0),
            (skillType.Crime, SkillLevel.None, 0)
        };
        List<(skillType Skill, bool have, int Experience)> generaleasyskills = new List<(skillType Skill, bool have, int Experience)>
        {
            (skillType.Piloting, false, 0),
            (skillType.Botany, false, 0),
            (skillType.MusInstruments, false, 0),
            (skillType.Bureaucracy, false, 0),
            (skillType.Atmosphere, false, 0)
        };
        int skillpoints = -SkillpointCredit;

        void ApplyBasicSkills(Dictionary<skillType, SkillLevel>? backgroundSkills)
        {
            if (backgroundSkills == null)
                return;

            foreach (var (skill, level) in backgroundSkills)
            {
                int index = generalbasicskills.FindIndex(s => s.Skill == skill);
                if (index == -1)
                    continue;

                var current = generalbasicskills[index];
                int total = (int)current.Level + (int)level;
                SkillLevel newLevel = total > (int)SkillLevel.Expert
                    ? SkillLevel.Expert
                    : (SkillLevel)total;

                if (total > (int)SkillLevel.Expert)
                    skillpoints += total - (int)SkillLevel.Expert;

                generalbasicskills[index] = (skill, newLevel, 0);
            }
        }

        void ApplyEasySkills(HashSet<skillType>? backgroundSkills)
        {
            if (backgroundSkills == null)
                return;

            foreach (var skill in backgroundSkills)
            {
                int index = generaleasyskills.FindIndex(s => s.Skill == skill);
                if (index == -1)
                    continue;

                var current = generaleasyskills[index];
                if (current.have)
                {
                    skillpoints += 1;
                }
                else
                {
                    generaleasyskills[index] = (skill, true, 0);
                }
            }
        }

        //Собираем в кучу навыки со всех предысторий а также от выбора игрока
        ApplyBasicSkills(BabyBackgroundBasicSkills);
        ApplyBasicSkills(AdultBackgroundBasicSkills);
        ApplyBasicSkills(GeneralBackgroundBasicSkills);
        ApplyBasicSkills(addedbasicskills);

        ApplyEasySkills(BabyBackgroundEasySkills);
        ApplyEasySkills(AdultBackgroundEasySkills);
        ApplyEasySkills(GeneralBackgroundEasySkills);
        ApplyEasySkills(addedeasyskills);
        //Основные навыки
        foreach (var (skillName, level, experience) in generalbasicskills)
        {
            var skillControl = new SkillControl(skillName, level, experience, skillpoints > 0);
            skillControl.OnPressed += () => AddSkill(skillName, collection);

            BasicSkillContainer.Children.Add(skillControl);
        }
        //Лёгкие навыки
        foreach (var (skillName, have, experience) in generaleasyskills)
        {   
            var easyskillsControl = new EasyskillsControl(skillName, have, experience, false );
            easyskillsControl.OnPressed += () => AddSkill(skillName, collection);

            EasySkillContainer.Children.Add(easyskillsControl);
        }
        //Скиллпоинты
        if(skillpoints>0)
        {
            var skillpointMessage = new FormattedMessage();
            skillpointMessage.AddMarkupOrThrow(Loc.GetString("rolebackground-ui-SkillPoints", ("count", skillpoints) ));
            Skillpoints.SetMessage(skillpointMessage);
            Skillpoints.Visible = true;
        }
    }
    private void AddSkill(skillType skillName, IDependencyCollection collection)
    {
        if (SkillComponent.IsEasySkill(skillName))
        {
            if (!addedeasyskills.Contains(skillName))
            {
                addedeasyskills.Add(skillName);
                SkillpointCredit++;
                RefreshInformation(collection);
            }
            return;
        }

        // Если не easy, значит basic
        if (addedbasicskills.TryGetValue(skillName, out var currentLevel))
        {
            if ((int)currentLevel < (int)SkillLevel.Expert)
                addedbasicskills[skillName] = currentLevel + 1;
        }
        else
        {
            addedbasicskills[skillName] = SkillLevel.Basic;
        }

        SkillpointCredit++;
        RefreshInformation(collection);
    }




    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.None;
    }
}
