using System.Linq;
using Content.Corvax.Interfaces.Shared;
using Content.Shared.Clothing;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Content.Client.Vanilla.Background;
using Content.Shared.Vanilla.Background;
using Content.Client.Vanilla.UserInterface.Background;

namespace Content.Client.Vanilla.UserInterface.Lobby.BackgroundUI;

[GenerateTypedNameReferences]
public sealed partial class BackgroundGroupContainer : BoxContainer
{
    public event Action<ProtoId<BackgroundPrototype>, ProtoId<BackgroundGroupPrototype>>? OnBackgroundSelected;

    public BackgroundGroupContainer(IDependencyCollection collection, BackgroundGroupPrototype groupProto)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var protoMan = collection.Resolve<IPrototypeManager>();
        var backgroundSystem = collection.Resolve<IEntityManager>().System<SharedBackgroundSystem>();

        BackgroundsContainer.DisposeAllChildren();
        var groupbackgrounds = groupProto.Backgrounds;

        foreach (var bgId in groupbackgrounds)
        {
            if (!protoMan.TryIndex(bgId, out var bgProto))
                continue;

            var control = new BackgroundControl(
                bgProto.Name,
                bgProto.Description,
                bgProto.SpecialDesc,
                bgProto.Skills,
                bgProto.EasySkills,
                bgProto.SkillPoints
            );

            control.OnPressed += () => OnBackgroundSelected?.Invoke(bgId, groupProto.ID);
            BackgroundsContainer.AddChild(control);
        }
    }

}