using Content.Shared.Vanilla.Entities.ArsenalAuthorizator;
using Content.Shared.Vanilla.AlertKey;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.TurretController;
using Content.Shared.Turrets;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Numerics;
using System.Linq;

namespace Content.Client.Vanilla.Entities.ArsenalAuthorizator;

[GenerateTypedNameReferences]
public sealed partial class ArsenalAuthorizatorWindow : BaseWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    [Dependency] private readonly IResourceCache _cache = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    private readonly SharedArsenalAuthorizatorSystem _arsenal;

    private EntityUid? _owner;
    private string? SelectedReason = null;
    private ArsenalAuthorizatorState State = ArsenalAuthorizatorState.Green;
    private readonly ButtonGroup _reasonButtons = new();
    public event Action<string>? OnArsenalAuthorizatorButtonPressed;

    public ArsenalAuthorizatorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _arsenal = _entManager.System<SharedArsenalAuthorizatorSystem>();
        CloseButton.OnPressed += _ => Close();

        OpenButton.OnToggled += _ => OnOpenButtonPressed();

        OpenButton.Label.AddStyleClass("ConsoleText");

        Footer.FontOverride = _cache.NotoStack(size: 8);
    }


    private void OnOpenButtonPressed()
    {
        if (SelectedReason == null)
            return;

        OnArsenalAuthorizatorButtonPressed?.Invoke(SelectedReason);
    }


    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
        Initialize();
    }

    private void Initialize()
    {

        if (_entManager.TryGetComponent<ArsenalAuthorizatorComponent>(_owner, out var comp))
            State = comp.State;
        UpdateOpenReasons();
        UpdateOpenButton();
        UpdateTheme();
    }


    public void UpdateState()
    {
        if (_entManager.TryGetComponent<ArsenalAuthorizatorComponent>(_owner, out var comp))
            State = comp.State;
        UpdateOpenReasons();
        UpdateOpenButton();
        UpdateTheme();
    }


    private void UpdateTheme()
    {
        ContentsContainer.Modulate = _arsenal.GetColor(State);
    }


    private void UpdateOpenButton()
    {
        OpenButton.Pressed = State != ArsenalAuthorizatorState.Green;
        var canInteract = IsLocalPlayerAllowedToInteract();
        OpenButton.Disabled = !canInteract || SelectedReason == null;
    }

    public void UpdateOpenReasons()
    {
        var allreasons = _proto.EnumeratePrototypes<AlertLevelReasonPrototype>().ToArray();
        int reasonsCount = 0;
        ReasonsContainer.RemoveAllChildren();

        foreach (var reason in allreasons)
        {
            if (reason.Code != "red")
                continue;

            var reasonButton = new MonotoneButton
            {
                Text = reason.Text,
                StyleClasses = { "OpenBoth" },
                Pressed = false,
                ToggleMode = true,
                HorizontalExpand = true,
                Group = _reasonButtons,
                Disabled = !IsLocalPlayerAllowedToInteract()
            };

            reasonButton.OnToggled += args => SelectReason(reason.ID);
            reasonButton.Label.AddStyleClass("ConsoleText");
            ReasonsContainer.AddChild(reasonButton);
            reasonsCount++;
        }

        var hasReasons = reasonsCount > 0;
        NoReasonsText.Visible = !hasReasons;
        ReasonsContainer.Visible = hasReasons;
        ReasonStatusHeader.Text = Loc.GetString("arsenal-authorizator-reasons-label", ("count", reasonsCount));
    }


    private void SelectReason(string id)
    {
        SelectedReason = id;
        UpdateOpenButton();
    }


    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }

    private bool IsLocalPlayerAllowedToInteract()
    {
        if (_owner == null || _playerManager.LocalSession?.AttachedEntity == null)
            return false;

        return _arsenal.IsUserAllowedAccess(_owner.Value, _playerManager.LocalSession.AttachedEntity.Value);
    }
}
