using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Access.Components;
using Content.Shared.CCVar;
using Content.Shared.Security.Components;
using Content.Client.Vanilla.UserInterface.LawControls;
using Content.Shared.Vanilla.Bureaucracy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client.Security.Ui;
/*
    ЧТО БЫ ТУТ НЕ ПРОИСХОДИЛО ЭТОТ КОД ДОЛЖЕН ОСТАВАТЬСЯ ТЕМ ЖЕ ЧТО И БЫЛ.
*/
[GenerateTypedNameReferences]
public sealed partial class GenpopLockerMenu : FancyWindow
{
    [Dependency] private readonly IConfigurationManager _cfgManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public event Action<string, float, string>? OnConfigurationComplete;
    private readonly Dictionary<int, LawInfoPrototype> _selectedLaws = new();
    private readonly Dictionary<int, LawControl> _selectedControls = new();


    public GenpopLockerMenu(EntityUid owner, IEntityManager entMan)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Title = entMan.GetComponent<MetaDataComponent>(owner).EntityName;

        NameLabel.SetMarkup(Loc.GetString("genpop-locker-ui-label-name"));
        SentenceLabel.SetMarkup(Loc.GetString("genpop-locker-ui-label-sentence"));
        CrimeLabel.SetMarkup(Loc.GetString("genpop-locker-ui-label-crime"));

        //таблица законов
        LawsContainer.Children.Clear();
        _selectedControls.Clear();
        _selectedLaws.Clear();
        var laws = PopulateLaws();

        for (int r = 0; r < laws.Count; r++)
        {
            for (int c = 0; c < laws[r].Count; c++)
            {
                var proto = laws[r][c];

                // 1. Заголовки первой строки
                if (r == 0)
                {
                    string header = c == 0 ? "Код" : $"{c}xx";
                    var ctrl = new LawControl(header, false);
                    LawsContainer.Children.Add(ctrl);
                    continue;
                }

                // 2. Заголовки первой колонки
                if (c == 0)
                {
                    string header = $"{r - 1:00}";
                    var ctrl = new LawControl(header, false);
                    LawsContainer.Children.Add(ctrl);
                    continue;
                }

                // 3. Пустая клетка
                if (proto == null)
                {
                    var ctrl = new LawControl("", false);
                    LawsContainer.Children.Add(ctrl);
                    continue;
                }

                // 4. Закон
                var lawControl = new LawControl(proto.Name, true, proto.Desc);
                var localProto = proto;        // замыкание!
                var localControl = lawControl; // замыкание!

                lawControl.OnPressed += () => AddLaw(localProto, localControl);

                LawsContainer.Children.Add(lawControl);
            }
        }

        var maxIdJobLength = _cfgManager.GetCVar(CCVars.MaxIdJobLength);
        NameEdit.IsValid = val => val.Length <= maxIdJobLength;
        SentenceEdit.IsValid = val => (float.TryParse(val, out var f) && f >= 0) || val == "Пожизненное заключение" || val == "Казнь";
        CrimeEdit.IsValid = val => val.Length <= GenpopLockerComponent.MaxCrimeLength;

        NameEdit.OnTextChanged += _ => OnTextEdit();
        SentenceEdit.OnTextChanged += _ => OnTextEdit();
        CrimeEdit.OnTextChanged += _ => OnTextEdit();

        DoneButton.OnPressed += _ =>
        {
            float duration = (SentenceEdit.Text == "Пожизненное заключение" || SentenceEdit.Text == "Казнь") ? 0 : float.Parse(SentenceEdit.Text);
            OnConfigurationComplete?.Invoke(NameEdit.Text, duration, CrimeEdit.Text);
        };
    }
    private void AddLaw(LawInfoPrototype law, LawControl control)
    {
        // --- Controls ---
        if (_selectedControls.TryGetValue(law.Category, out var oldControl))
            oldControl.MainButton.ModulateSelfOverride = null;

        if (ToggleValue(_selectedControls, law.Category, control))
            control.MainButton.ModulateSelfOverride = Color.FromHex("#173012ff");

        // --- Laws ---
        ToggleValue(_selectedLaws, law.Category, law);

        RecalculateSentence();
    }
    private void RecalculateSentence()
    {
        if (_selectedLaws.Count == 0)
        {
            SentenceEdit.Clear();
            CrimeEdit.Clear();
            return;
        }

        // находим основную статью
        LawInfoPrototype mainLaw = _selectedLaws.Values
            .OrderByDescending(l => l.Danger)
            .First();

        if (mainLaw.Danger == 5)
        {
            SentenceEdit.Text = "Пожизненное заключение";
            CrimeEdit.Text = Loc.GetString(mainLaw.Name);
            return;
        }
        if (mainLaw.Danger == 6)
        {
            SentenceEdit.Text = "Казнь";
            CrimeEdit.Text = Loc.GetString(mainLaw.Name);
            return;
        }

        int totalTime = mainLaw.BaseTime;

        List<int> codes = new() { mainLaw.Code };

        // дополнительные статьи
        foreach (var law in _selectedLaws.Values)
        {
            if (law == mainLaw)
                continue;

            totalTime += law.BaseTime / 2;
            codes.Add(law.Code);
        }

        CrimeEdit.Text = string.Join(", ", codes);
        SentenceEdit.Text = totalTime.ToString();
    }

    private void OnTextEdit()
    {
        bool disabled = false;

        // пустые поля
        if (string.IsNullOrWhiteSpace(NameEdit.Text) ||
            string.IsNullOrWhiteSpace(CrimeEdit.Text))
        {
            disabled = true;
        }

        string s = SentenceEdit.Text;

        if (s != "Пожизненное заключение" && s != "Казнь")
        {
            if (!float.TryParse(s, out float sentence) || sentence < 0)
                disabled = true;
        }

        DoneButton.Disabled = disabled;
    }
    private List<List<LawInfoPrototype?>> PopulateLaws()
    {
        const int cols = 7;
        const int rows = 7;

        var map = new Dictionary<(int col, int danger), LawInfoPrototype>();

        foreach (var proto in _prototypeManager.EnumeratePrototypes<LawInfoPrototype>())
        {
            map[(proto.Category, proto.Danger)] = proto;
        }

        var table = new List<List<LawInfoPrototype?>>();

        table.Add(new List<LawInfoPrototype?> { null, null, null, null, null, null, null });

        for (int j = 0; j < rows; j++)
        {
            var row = new List<LawInfoPrototype?>();

            for (int i = 0; i < cols; i++)
            {
                map.TryGetValue((j, i), out var law);
                row.Add(law);
            }

            table.Add(row);
        }

        return table;
    }





    private static bool ToggleValue<T>(Dictionary<int, T> dict, int key, T value)
    {
        if (dict.TryGetValue(key, out var old))
        {
            dict.Remove(key);
            if (!EqualityComparer<T>.Default.Equals(old, value))
            {
                dict[key] = value;
                return true;
            }
            return false;
        }

        dict[key] = value;
        return true;
    }

}

