using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{
    public GhostTargetWindow TargetWindow { get; }

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? GhostRolesPressed;
    public event Action? TDMArenaButtonPressed;
    public event Action? TTTArenaButtonPressed;
    private int _prevNumberRoles;

    public GhostGui()
    {
        RobustXamlLoader.Load(this);

        TargetWindow = new GhostTargetWindow();

        MouseFilter = MouseFilterMode.Ignore;

        TDMArenaButton.OnPressed += _ => TDMArenaButtonPressed?.Invoke();//RAYTEN
        TTTArenaButton.OnPressed += _ => TTTArenaButtonPressed?.Invoke();//RAYTEN

        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesButton.StyleClasses.Remove(StyleBase.ButtonCaution);
    }

    public void Hide()
    {
        TargetWindow.Close();
        Visible = false;
    }

    public void Update(int? roles, bool? canReturnToBody)
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;

        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));

            if (roles > _prevNumberRoles)
            {
                GhostRolesButton.StyleClasses.Add(StyleBase.ButtonCaution);
            }

            _prevNumberRoles = (int)roles;
        }

        TargetWindow.Populate();
    }
    public void TDMUpdate(TimeSpan TimeToNewCycle, int tdmwannajoin)
    {
        if (TimeToNewCycle <= TimeSpan.FromSeconds(-1))
        {
            TDMArenaButton.Text = Loc.GetString("TDM-NotAvailable");
            TDMArenaButton.Disabled = true;
        }
        else
        {
            int blueguys = (tdmwannajoin % 2 == 1) ? tdmwannajoin / 2 + 1 : tdmwannajoin / 2;
            int redguys = tdmwannajoin / 2;
            TDMArenaButton.Text = Loc.GetString("TDM-Available", ("blueguys", blueguys), ("redguys", redguys), ("timer", TimeToNewCycle));
            TDMArenaButton.Disabled = false;
        }
    }
    public void TTTUpdate(TimeSpan TimeToNewCycle, int TTTwannajoin)
    {
        if (TimeToNewCycle <= TimeSpan.FromSeconds(-1))
        {
            TTTArenaButton.Text = Loc.GetString("TTT-NotAvailable");
            TTTArenaButton.Disabled = true;
        }
        else
        {
            TTTArenaButton.Text = Loc.GetString("TTT-Available", ("players", TTTwannajoin), ("timer", TimeToNewCycle));
            TTTArenaButton.Disabled = false;
        }
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
        }
    }
}
