using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Client.ResourceManagement;
using Content.Shared.Vanilla.Skill;

namespace Content.Client.UserInterface.Systems.Character.Easyskills;

[GenerateTypedNameReferences]
public sealed partial class EasyskillsControl : Control
{
    private int _exp = 0;
    public Action? OnPressed;

    public EasyskillsControl(skillType SkillName, bool have, int exp, bool haveskillpoint)
    {
        RobustXamlLoader.Load(this);
        var resCache = IoCManager.Resolve<IResourceCache>();
        var iconlvl = resCache.GetResource<TextureResource>("/Textures/Vanilla/Interface/SkillLvlIcons/EasySkillAmnesia.png");
        var skillinfomessage = new FormattedMessage();
        var skillnamemessage = new FormattedMessage();
        _exp = exp;

        skillnamemessage.AddMarkupOrThrow(Loc.GetString("skill-system-UI-SkillNameLabel", ("skillname", SkillName.ToString())));

        if(have)
        {
            iconlvl = resCache.GetResource<TextureResource>("/Textures/Vanilla/Interface/SkillLvlIcons/EasySkillYes.png");
            skillinfomessage.AddMarkupOrThrow(Loc.GetString("skill-system-UI-Easy-SkillInfoLabel-Have"));
        }
        else
        {
            iconlvl = resCache.GetResource<TextureResource>("/Textures/Vanilla/Interface/SkillLvlIcons/EasySkillNo.png");
            skillinfomessage.AddMarkupOrThrow(Loc.GetString("skill-system-UI-Easy-SkillInfoLabel", ("exp", _exp), ("amnesia", "") ));
        }
        SkillTexture.Texture = iconlvl;
        InfoLabel.SetMessage(skillinfomessage);
        SkillNameLabel.SetMessage(skillnamemessage);

        MainButton.Disabled = !haveskillpoint || have;
        MainButton.OnPressed += _ => OnPressed?.Invoke();
        AmnesiaLabel.Visible= false;
        MainButton.ToolTip = Loc.GetString($"skill-system-UI-Tooltip-{SkillName.ToString()}");
    }

    public void updateamnesia(skillType skill, int exptorestore)
    {
        var resCache = IoCManager.Resolve<IResourceCache>();
        var Amnesiamessage = new FormattedMessage();


        Amnesiamessage.AddMarkupOrThrow(Loc.GetString("skill-system-UI-Easy-AmnesiaLabel", ("exptorestore", exptorestore) ));
        var iconlvl = resCache.GetResource<TextureResource>("/Textures/Vanilla/Interface/SkillLvlIcons/EasySkillAmnesia.png");


        AmnesiaLabel.SetMessage(Amnesiamessage);
        SkillTexture.Texture = iconlvl;
        AmnesiaLabel.Visible= true;
    }
}