using Content.Shared.Vanilla.CCVars;
using Content.Client.Overlays;
using Content.Shared.Overlays;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared;

namespace Content.Client.Vanilla.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class HorrorTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public HorrorTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Control.AddOptionPercentSlider(CCVVars.GrainStrength, GrainStrengthSlider,
            0.0f, 2.0f);
        Control.AddOptionPercentSlider(CCVVars.SinCitySaturation, SinCityStrengthSlider,
            0.0f, 1.0f);

        Control.Initialize();
    }
}
