using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls; // Добавьте это, если его нет

namespace Content.Client.UserInterface.Systems.Character.Windows;

[GenerateTypedNameReferences]
public sealed partial class CharacterWindow : DefaultWindow
{
    public CharacterWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
