- type: startingGear
  id: SkeletonJester
  equipment:
    head: ClothingHeadHatRedwizard
    outerClothing: ClothingOuterWizardRed
    shoes: ClothingShoesWizard

- type: startingGear
  id: SkeletonKnight
  equipment:
    head: ClothingHeadHatRedwizard
    outerClothing: ClothingOuterWizardRed
    shoes: ClothingShoesWizard
