using Content.Shared.Vanilla.Competitive;
using Content.Shared.Containers.ItemSlots;
using Content.Shared.Research.Components;
using Content.Client.UserInterface.Controls;
using Robust.Shared.Utility;
using Robust.Shared.Audio;
using Robust.Shared.Player;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using JetBrains.Annotations;
using System.Linq;

namespace Content.Client.Vanilla.TechAnalysis;

[GenerateTypedNameReferences]
public sealed partial class TechnicalAnalysisMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly AudioSystem _audio;
    private readonly ItemSlotsSystem _slots;
    public event Action<List<char>>? OnSubmitPressed;
    public event Action? OnFullResetPressed;
    public event Action? OnExtractPressed;
    public event Action? OnServerSelectionButtonPressed;
    private bool ForceDisableSubmitBtn = false;
    public TechnicalAnalysisMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _slots = _entityManager.System<ItemSlotsSystem>();
        _audio = _entityManager.System<AudioSystem>();

        SubmitButton.OnPressed += _ =>
        {
            var guess = GetSubmittedGenome();
            SubmitButton.Disabled = true;
            OnSubmitPressed?.Invoke(guess);
        };

        ExtractButton.OnPressed += _ =>
        {
            ExtractButton.Disabled = true;
            OnExtractPressed?.Invoke();
        };
        ServerButton.OnPressed += _ =>
        {
            OnServerSelectionButtonPressed?.Invoke();
        };
        FullResetButton.OnPressed += _ => OnFullResetPressed?.Invoke();
        ResetButton.OnPressed += _ => ResetGenomeButtons();
    }
    public void NoItem(bool noitem)
    {
        RightPanel.Visible = !noitem;
        NoItemPanel.Visible = noitem;
        AttemptsLeftLabel.Visible = !noitem;
        if (noitem)
        {
            FullResetButton.Disabled = true;
            Difficult.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("TechnicalAnalysis-ui-difficult", ("difficult", "error"))));
        }
    }
    public void ExtractButtonUpdate(int points)
    {
        ExtractButton.Disabled = points <= 0;

        if (points == -1)
        {
            ServerConnectionStatus.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("TechnicalAnalysis-ui-server-notconnected")));
        }
        else
        {
            ServerConnectionStatus.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("TechnicalAnalysis-ui-server-connected")));
            PointsLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(
                Loc.GetString("TechnicalAnalysis-ui-researchpoints-count", ("points", points))));
        }

    }


    public void Update(List<List<CodonFeedBack>> history, int attemptscount, string itemname, LocId sourceDesc, CompetitiveDifficult diffictult)
    {
        int buttoncount = diffictult == CompetitiveDifficult.easy ? 4 : 6;
        CreateGenomeInputControls(buttoncount);
        UpdateHistory(history);
        UpdateWinCondition(attemptscount);
        UpdateSubmitButtonState();

        ItemDesc.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString(sourceDesc)));
        ItemName.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("TechnicalAnalysis-ui-itemname", ("item", itemname))));
        Difficult.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("TechnicalAnalysis-ui-difficult", ("difficult", diffictult.ToString()))));
        FullResetButton.Disabled = diffictult == CompetitiveDifficult.hard;
    }

    public void UpdateHistory(List<List<CodonFeedBack>> history)
    {
        HistoryContainer.RemoveAllChildren();

        foreach (var attempt in history)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalAlignment = HAlignment.Center,
                HorizontalExpand = true,
            };

            foreach (var feedback in attempt)
            {
                var button = new Button
                {
                    Text = feedback.Codon.ToString(),
                    MinWidth = 50,
                    MinHeight = 50,
                    Disabled = true,
                };

                switch (feedback.Hint)
                {
                    case CodonHint.Correct:
                        button.Modulate = Color.FromHex("#4CAF50"); // зеленый
                        break;
                    case CodonHint.WrongPosition:
                        button.Modulate = Color.FromHex("#FFC107"); // желтый
                        break;
                    case CodonHint.Incorrect:
                        button.Modulate = Color.FromHex("#F44336"); // красный
                        break;
                }

                row.AddChild(button);
            }

            HistoryContainer.AddChild(row);
        }
        UpdateGenomeInputFromHistory(history);
    }
    public void UpdateWinCondition(int attemptcount)
    {
        AttemptsLeftLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("TechnicalAnalysis-ui-attempts", ("count", attemptcount))));

        //проиграли
        if (attemptcount <= 0)
        {
            ForceDisableSubmitBtn = true;
            return;
        }
        //играем
        ForceDisableSubmitBtn = false;

    }

    public void CreateGenomeInputControls(int buttoncount)
    {
        GenomeGrid.RemoveAllChildren();

        for (int i = 0; i < buttoncount; i++)
        {
            var button = new Button
            {
                Text = "?",
                MinWidth = 50,
                MinHeight = 50,
            };

            int index = i;
            button.OnPressed += _ => CycleLetter(button, index);

            GenomeGrid.AddChild(button);
        }
    }

    private void CycleLetter(Button button, int index)
    {
        var letters = new[] { 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H' };

        var usedLetters = GenomeGrid.Children
            .OfType<Button>()
            .Select((b, i) => (Button: b, Index: i))
            .Where(x => x.Index != index && x.Button.Text is { Length: 1 })
            .Select(x => x.Button.Text![0])
            .ToHashSet();

        var currentText = button.Text;
        char current = (currentText != null && currentText.Length == 1) ? currentText[0] : '?';
        int idx = Array.IndexOf(letters, current);

        for (int i = 0; i < letters.Length; i++)
        {
            idx = (idx + 1) % letters.Length;
            if (!usedLetters.Contains(letters[idx]))
            {
                button.Text = letters[idx].ToString();
                SoundSpecifier keySound = new SoundCollectionSpecifier("Keyboard");
                _audio.PlayGlobal(keySound, Filter.Local(), false);
                UpdateSubmitButtonState();
                return;
            }
        }

        button.Text = "?";
        UpdateSubmitButtonState();
    }

    public List<char> GetSubmittedGenome()
    {
        var result = new List<char>();
        foreach (var child in GenomeGrid.Children)
        {
            if (child is Button btn && btn.Text != null && btn.Text.Length == 1)
            {
                result.Add(btn.Text[0]);
            }
        }
        return result;
    }

    private void UpdateGenomeInputFromHistory(List<List<CodonFeedBack>> history)
    {
        if (history.Count == 0)
            return;

        var lastAttempt = history[^1]; // Последняя попытка

        int buttonCount = GenomeGrid.Children.Count();
        var codonCount = lastAttempt.Count;
        var count = Math.Min(6, Math.Min(buttonCount, codonCount));

        for (int i = 0; i < count; i++)
        {
            if (GenomeGrid.Children.ElementAt(i) is not Button button)
                continue;

            var feedback = lastAttempt[i];

            if (feedback.Hint == CodonHint.Correct)
            {
                button.Modulate = Color.FromHex("#4CAF50"); // зелёный
                button.Text = feedback.Codon.ToString();
                button.Disabled = true;
            }
            else
            {
                button.Disabled = false;
            }
        }
    }

    private void ResetGenomeButtons()
    {
        foreach (var child in GenomeGrid.Children)
        {
            if (child is Button button)
            {
                if (!button.Disabled)
                    button.Text = "?";
            }
        }
    }

    private void UpdateSubmitButtonState()
    {
        if (ForceDisableSubmitBtn)
            SubmitButton.Disabled = true;

        var isValid = GenomeGrid.Children
            .OfType<Button>()
            .All(b => b.Text is { Length: 1 } && b.Text != "?");

        SubmitButton.Disabled = !isValid;
    }


}
