using Content.Shared.Vanilla.AlertKey;
using Content.Client.UserInterface.Controls;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Content.Client.Vanilla.UserInterface.AlertKey
{
    [GenerateTypedNameReferences]
    public sealed partial class AlertKeyMenu : FancyWindow
    {
        [Dependency] private readonly IPrototypeManager _proto = default!;

        public bool AlertLevelSelectable;
        public event Action<string?, string?, string?>? OnApply;
        public List<(string Level, bool IsSubcode, bool blocked)>? Alerts;
        private string? subcodestoadd = null;
        private string? SelectedReason = null;
        private string? _selectedMainLevel = null;

        public AlertKeyMenu()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            var allreasons = _proto.EnumeratePrototypes<AlertLevelReasonPrototype>().ToList();

            ApplyButton.Disabled = !AlertLevelSelectable || SelectedReason == null;

            MainSelection.OnItemSelected += args =>
            {
                SelectedReason = null;
                ApplyButton.Disabled = !AlertLevelSelectable || SelectedReason == null;

                ReasonContainer.Children.Clear();
                _selectedMainLevel = MainSelection.GetItemMetadata(args.Id) as string;

                UpdateMainSelection(_selectedMainLevel);

                var buttonList = new List<Button>();

                foreach (var reason in allreasons)
                {
                    if (_selectedMainLevel != reason.Code)
                        continue;

                    var reasonButton = new Button()
                    {
                        Text = reason.Text,
                        StyleClasses = { "chatSelectorOptionButton" },
                    };

                    reasonButton.OnPressed += _ =>
                    {
                        if (SelectedReason == reason.ID)
                        {
                            SelectedReason = null;
                            ApplyButton.Disabled = !AlertLevelSelectable || SelectedReason == null;

                            foreach (var btn in buttonList)
                                btn.Disabled = false;
                        }
                        else
                        {
                            SelectedReason = reason.ID;
                            ApplyButton.Disabled = !AlertLevelSelectable || SelectedReason == null;

                            foreach (var btn in buttonList)
                                btn.Disabled = true;

                            reasonButton.Disabled = false;
                        }
                    };

                    ReasonContainer.AddChild(reasonButton);
                    buttonList.Add(reasonButton);
                }
            };

            ApplyButton.OnPressed += _ =>
            {
                OnApply?.Invoke(_selectedMainLevel, subcodestoadd, SelectedReason);
            };

        }

        // Обработчик для переключения состояния подуровней
        private void OnSubLevelToggled(string level, bool isPressed)
        {
            SelectedReason = null;
            ApplyButton.Disabled = !AlertLevelSelectable || SelectedReason == null;
            ReasonContainer.Children.Clear();

            if (isPressed)
            {
                subcodestoadd = level;

                var allreasons = _proto.EnumeratePrototypes<AlertLevelReasonPrototype>().ToList();
                var buttonList = new List<Button>();

                foreach (var reason in allreasons)
                {
                    if (_selectedMainLevel != reason.Code)
                        continue;

                    var reasonButton = new Button()
                    {
                        Text = reason.Text,
                        StyleClasses = { "chatSelectorOptionButton" },
                    };

                    reasonButton.OnPressed += _ =>
                    {
                        if (SelectedReason == reason.ID)
                        {
                            // Отмена выбора
                            SelectedReason = null;
                            ApplyButton.Disabled = true;

                            // Разблокировать все кнопки
                            foreach (var btn in buttonList)
                                btn.Disabled = false;
                        }
                        else
                        {
                            // Выбран новый reason
                            SelectedReason = reason.ID;
                            ApplyButton.Disabled = !AlertLevelSelectable || SelectedReason == null;

                            // Заблокировать все, кроме текущей
                            foreach (var btn in buttonList)
                                btn.Disabled = true;

                            reasonButton.Disabled = false;
                        }
                    };

                    ReasonContainer.AddChild(reasonButton);
                    buttonList.Add(reasonButton);
                }
            }
            else
            {
                subcodestoadd = null;
            }
        }


        public void UpdateAlertLevels(List<(string Level, bool IsSubcode, bool blocked)>? alerts, string currentAlert, HashSet<string> ActiveSubLevels)
        {
            MainSelection.Clear();
            SubLevelContainer.RemoveAllChildren();
            _selectedMainLevel = currentAlert;
            if (alerts == null)
            {
                // Если список пуст, добавляем только текущий основной код
                AddMainLevel(currentAlert);
            }
            else
            {
                // Проходим по всем уровням
                foreach (var (level, IsSubcode, blocked) in alerts)
                {
                    if (IsSubcode)
                        CreateSubLevelButton(level, ActiveSubLevels.Contains(level), blocked);
                    else
                        AddMainLevel(level, currentAlert);
                }
            }
        }
        private void UpdateMainSelection(string? selectedLevel)
        {
            // Очищаем текущие элементы
            MainSelection.Clear();

            // Перезаполняем выпадающий список с новыми уровнями
            if (Alerts != null)
            {
                foreach (var (level, isSubcode, _) in Alerts)
                {
                    if (!isSubcode)  // Добавляем только основные уровни
                    {
                        AddMainLevel(level, selectedLevel);
                    }
                }
            }
        }

        // Добавляем основной уровень угроз
        private void AddMainLevel(string level, string? selectedLevel = null)
        {
            if (Alerts == null)
                return;

            var alert = Alerts.FirstOrDefault(a => a.Level == level);
            if (alert == default)
                return;

            var name = Loc.GetString($"alert-level-{level}");
            MainSelection.AddItem(name);
            int index = MainSelection.ItemCount - 1; // Получаем индекс последнего добавленного элемента

            MainSelection.SetItemMetadata(index, level);

            // Если уровень заблокирован — делаем его неактивным
            if (alert.blocked)
            {
                MainSelection.SetItemDisabled(index, true);
            }
            else if (level == selectedLevel)
            {
                MainSelection.Select(index);
            }
        }

        // Создаем кнопку для подуровня
        private void CreateSubLevelButton(string level, bool isPressed, bool isblocked)
        {
            var button = new Button
            {
                Text = Loc.GetString($"alert-level-{level}"),
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = isPressed,
                Name = level,
                Disabled = (isblocked || !AlertLevelSelectable)
            };
            if(!isblocked) button.OnPressed += _ => OnSubLevelToggled(level, button.Pressed);
            SubLevelContainer.AddChild(button);
        }
    }
}
