using Content.Shared.Vanilla.AlertKey;
using Content.Client.UserInterface.Controls;
using Robust.Shared.Prototypes;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using System.Linq;

namespace Content.Client.Vanilla.UserInterface.AlertKey
{
    [GenerateTypedNameReferences]
    public sealed partial class AlertKeyMenu : FancyWindow
    {
        [Dependency] private IPrototypeManager _proto = default!;

        public bool AlertLevelSelectable;
        public event Action<string?, string?>? OnApply;
        private string? _subcodestoadd = null;
        private string? _selectedReason = null;
        private readonly Dictionary<string, Color> _colorMap = new()
        {
            { "green", Color.Green },
            { "blue", Color.DodgerBlue },
            { "violet", Color.Violet },
            { "yellow", Color.Yellow },
            { "red", Color.Red },
        };

        public AlertKeyMenu()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);
            ApplyButton.Disabled = !AlertLevelSelectable || _selectedReason == null;

            ApplyButton.OnPressed += _ =>
            {
                OnApply?.Invoke(_subcodestoadd, _selectedReason);
            };

        }

        // Обработчик для переключения состояния подуровней
        private void OnSubLevelToggled(string level, bool isPressed)
        {
            _selectedReason = null;
            ApplyButton.Disabled = !AlertLevelSelectable || _selectedReason == null;
            ReasonContainer.Children.Clear();

            if (isPressed)
            {
                _subcodestoadd = level;

                var allreasons = _proto.EnumeratePrototypes<AlertLevelReasonPrototype>().ToList();
                var buttonList = new List<Button>();

                foreach (var reason in allreasons)
                {
                    if (level != reason.Code)
                        continue;

                    var reasonButton = new Button()
                    {
                        Text = reason.Text,
                        StyleClasses = { "chatSelectorOptionButton" },
                    };
                    reasonButton.OnPressed += _ =>
                    {
                        if (_selectedReason == reason.ID)
                        {
                            // Отмена выбора
                            _selectedReason = null;
                            ApplyButton.Disabled = true;

                            // Разблокировать все кнопки
                            foreach (var btn in buttonList)
                            {
                                btn.Modulate = Color.White;
                                btn.Disabled = false;
                            }
                        }
                        else
                        {
                            // Выбран новый reason
                            _selectedReason = reason.ID;
                            ApplyButton.Disabled = !AlertLevelSelectable || _selectedReason == null;

                            // Заблокировать все, кроме текущей
                            foreach (var btn in buttonList)
                            {
                                btn.Modulate = Color.White;
                                btn.Disabled = true;
                            }

                            if (_colorMap.TryGetValue(level, out var color))
                                reasonButton.Modulate = color;
                            reasonButton.Disabled = false;
                        }
                    };

                    ReasonContainer.AddChild(reasonButton);
                    buttonList.Add(reasonButton);
                }
            }
            else
            {
                _subcodestoadd = null;
            }
        }


        public void UpdateAlertLevels(List<(string Level, bool IsSubcode, bool blocked)>? alerts, HashSet<string> activeSubLevels)
        {
            SubLevelContainer.RemoveAllChildren();
            if (alerts == null)
                return;

            foreach (var (level, isSubcode, blocked) in alerts)
            {
                if (isSubcode)
                    CreateSubLevelButton(level, activeSubLevels.Contains(level), blocked);
            }
        }

        // Создаем кнопку для подуровня
        private void CreateSubLevelButton(string level, bool isPressed, bool isblocked)
        {
            var button = new Button
            {
                Text = Loc.GetString($"alert-level-{level}"),
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = isPressed,
                Name = level,
                Disabled = (isblocked || !AlertLevelSelectable)
            };
            if (!isblocked) button.OnPressed += _ => OnSubLevelToggled(level, button.Pressed);
            SubLevelContainer.AddChild(button);
        }
    }
}
