using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Vanilla.Skill;
using Content.Shared.Vanilla.Background;
using Robust.Client.AutoGenerated;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client.Vanilla.UserInterface.Background;

[GenerateTypedNameReferences]
public sealed partial class BackgroundControl : Control
{
    public Action? OnPressed;
 
    public BackgroundControl(string name, string description, Dictionary<skillType, SkillLevel> skills, HashSet<BackgroundSpecial> Specials, HashSet<skillType> EasySkills)
    {
        RobustXamlLoader.Load(this);
        var BackgroundNameMessage = new FormattedMessage();
        var BackgroundDescMessage = new FormattedMessage();
        BackgroundNameMessage.AddMarkupOrThrow(Loc.GetString(name));
        BackgroundDescMessage.AddMarkupOrThrow(Loc.GetString(description));
        NameLabel.SetMessage(BackgroundNameMessage);
        DescriptionLabel.SetMessage(BackgroundDescMessage);

        IEnumerable<string> skillList;

        //Навыки
        var skillDescriptions = new List<string>();

        if (skills.Count > 0)
        {
            skillDescriptions.AddRange(
                skills.Select(skill => 
                    Loc.GetString(
                        "background-ui-Skills", 
                        ("skilltype", skill.Key.ToString()), 
                        ("lvl", (int)skill.Value)
                    )
                )
            );
        }

        if (EasySkills.Count > 0)
        {
            skillDescriptions.AddRange(
                EasySkills.Select(easyskill => 
                    Loc.GetString(
                        "background-ui-EasySkills", 
                        ("skilltype", easyskill.ToString())
                    )
                )
            );
        }
        string skillsText = string.Join(", ", skillDescriptions);
        var finalskillsText = Loc.GetString("background-ui-SkillsLabel-prefix", ("skills", skillsText));

        var skillMsg = new FormattedMessage();
        skillMsg.AddMarkupOrThrow(finalskillsText);
        SkillsLabel.SetMessage(skillMsg);
        //Особое
        if (Specials.Count > 0)
        {
            var SpecialsList = Specials.Select(special => Loc.GetString("background-ui-SpecialsLabel-special", ("special", special.ToString())));
            var SpecialsText = string.Join(", ", SpecialsList);

            var finalSpecialsText = Loc.GetString("background-ui-SpecialsLabel-prefix", ("specials", SpecialsText));

            var specialMsg = new FormattedMessage();
            specialMsg.AddMarkupOrThrow(finalSpecialsText);
            SpecialsLabel.SetMessage(specialMsg);
        }
        Button.OnPressed += _ => OnPressed?.Invoke();
    }
    public BackgroundControl(string name, string description)
    {
        RobustXamlLoader.Load(this);
        var BackgroundNameMessage = new FormattedMessage();
        var BackgroundDescMessage = new FormattedMessage();
        BackgroundNameMessage.AddMarkupOrThrow(Loc.GetString(name));
        BackgroundDescMessage.AddMarkupOrThrow(Loc.GetString(description));
        NameLabel.SetMessage(BackgroundNameMessage);
        DescriptionLabel.SetMessage(BackgroundDescMessage);
        Button.Visible = false;
    }
}