using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Vanilla.Skill;
using Content.Shared.Vanilla.Background;
using Content.Shared.Vanilla.Sponsor;
using Robust.Shared.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client.Vanilla.UserInterface.Background;

[GenerateTypedNameReferences]
public sealed partial class BackgroundControl : Control
{
    private bool _notallowed;
    public Action? OnPressed;
    private SharedSponsorManager? _sponsorsMgr;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    public BackgroundControl(string name, string description, List<string>? SpecialDesc, Dictionary<skillType, SkillLevel> skills, HashSet<skillType> EasySkills, int skillpoints, bool notallowed)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        var BackgroundNameMessage = new FormattedMessage();
        var BackgroundDescMessage = new FormattedMessage();
        BackgroundNameMessage.AddMarkupOrThrow($"[head=2][bold][italic]{Loc.GetString(name)}[/italic][/bold][/head]");
        BackgroundDescMessage.AddMarkupOrThrow(Loc.GetString(description));
        NameLabel.SetMessage(BackgroundNameMessage);
        DescriptionLabel.SetMessage(BackgroundDescMessage);

        IEnumerable<string> skillList;
        _notallowed = notallowed;
        //Навыки
        var skillDescriptions = new List<string>();

        if (skills.Count > 0)
        {
            skillDescriptions.AddRange(
                skills.Select(skill =>
                    Loc.GetString(
                        "background-ui-Skills",
                        ("skilltype", skill.Key.ToString()),
                        ("lvl", (int)skill.Value)
                    )
                )
            );
        }

        if (EasySkills.Count > 0)
        {
            skillDescriptions.AddRange(
                EasySkills.Select(easyskill =>
                    Loc.GetString(
                        "background-ui-EasySkills",
                        ("skilltype", easyskill.ToString())
                    )
                )
            );
        }
        if (skillpoints > 0)
            skillDescriptions.Add(Loc.GetString("background-ui-SkillPoints", ("count", skillpoints)));

        string skillsText = string.Join(" ", skillDescriptions);
        var finalskillsText = Loc.GetString("background-ui-SkillsLabel-prefix", ("skills", skillsText));

        var skillMsg = new FormattedMessage();
        skillMsg.AddMarkupOrThrow(finalskillsText);
        SkillsLabel.SetMessage(skillMsg);


        //Особое
        if (SpecialDesc != null && SpecialDesc.Count > 0)
        {
            var specialMsg = new FormattedMessage();
            specialMsg.PushMarkup(Loc.GetString("background-ui-specials-header"));
            foreach (var specialText in SpecialDesc)
            {
                specialMsg.PushMarkup(specialText);
            }
            SpecialsLabel.SetMessage(specialMsg);
        }

        Button.OnPressed += _ =>
        {
            OnPressed?.Invoke();
            Button.Disabled = true;
            Button.Text = "Выбрано";
        };

        if (notallowed)
        {
            Button.Text = "Недоступно";
            Line.Color = Color.Gold;
            Button.Disabled = true;
        }
    }

    public void refreshbtn()
    {
        if (_notallowed)
        {
            Button.Disabled = false;
            Button.Text = "Недоступно";
        }
        else
        {
            Button.Disabled = false;
            Button.Text = "Выбрать";
        }
    }

    public BackgroundControl(string name, string description)
    {
        _notallowed = true;
        RobustXamlLoader.Load(this);
        var BackgroundNameMessage = new FormattedMessage();
        var BackgroundDescMessage = new FormattedMessage();
        BackgroundNameMessage.AddMarkupOrThrow(Loc.GetString(name));
        BackgroundDescMessage.AddMarkupOrThrow(Loc.GetString(description));
        NameLabel.SetMessage(BackgroundNameMessage);
        DescriptionLabel.SetMessage(BackgroundDescMessage);
        Button.Visible = false;
    }
}
