using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Vanilla.Skill;
using Content.Shared.Vanilla.Background;
using Robust.Shared.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client.Vanilla.UserInterface.Background;

[GenerateTypedNameReferences]
public sealed partial class BackgroundControl : Control
{
    public Action? OnPressed;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    public BackgroundControl(string name, string description, List<string>? SpecialDesc, Dictionary<skillType, SkillLevel> skills, HashSet<skillType> EasySkills, int skillpoints)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        var BackgroundNameMessage = new FormattedMessage();
        var BackgroundDescMessage = new FormattedMessage();
        BackgroundNameMessage.AddMarkupOrThrow(Loc.GetString(name));
        BackgroundDescMessage.AddMarkupOrThrow(Loc.GetString(description));
        NameLabel.SetMessage(BackgroundNameMessage);
        DescriptionLabel.SetMessage(BackgroundDescMessage);

        IEnumerable<string> skillList;

        //Навыки
        var skillDescriptions = new List<string>();

        if (skills.Count > 0)
        {
            skillDescriptions.AddRange(
                skills.Select(skill => 
                    Loc.GetString(
                        "background-ui-Skills", 
                        ("skilltype", skill.Key.ToString()), 
                        ("lvl", (int)skill.Value)
                    )
                )
            );
        }

        if (EasySkills.Count > 0)
        {
            skillDescriptions.AddRange(
                EasySkills.Select(easyskill => 
                    Loc.GetString(
                        "background-ui-EasySkills", 
                        ("skilltype", easyskill.ToString())
                    )
                )
            );
        }
        if (skillpoints > 0)
            skillDescriptions.Add(Loc.GetString("background-ui-SkillPoints", ("count", skillpoints)));

        string skillsText = string.Join(" ", skillDescriptions);
        var finalskillsText = Loc.GetString("background-ui-SkillsLabel-prefix", ("skills", skillsText));

        var skillMsg = new FormattedMessage();
        skillMsg.AddMarkupOrThrow(finalskillsText);
        SkillsLabel.SetMessage(skillMsg);


        //Особое
        if (SpecialDesc != null && SpecialDesc.Count > 0)
        {
            var specialMsg = new FormattedMessage();
            specialMsg.PushMarkup(Loc.GetString("background-ui-specials-header"));
            foreach (var specialText in SpecialDesc)
            {
                specialMsg.PushMarkup(specialText);
            }
            SpecialsLabel.SetMessage(specialMsg);
        }

        Button.OnPressed += _ => OnPressed?.Invoke();
    }
    public BackgroundControl(string name, string description)
    {
        RobustXamlLoader.Load(this);
        var BackgroundNameMessage = new FormattedMessage();
        var BackgroundDescMessage = new FormattedMessage();
        BackgroundNameMessage.AddMarkupOrThrow(Loc.GetString(name));
        BackgroundDescMessage.AddMarkupOrThrow(Loc.GetString(description));
        NameLabel.SetMessage(BackgroundNameMessage);
        DescriptionLabel.SetMessage(BackgroundDescMessage);
        Button.Visible = false;
    }
}