using Content.Client.GameTicking.Managers;
using Content.Shared.Store;
using Content.Shared.Contraband;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
namespace Content.Client.Store.Ui;

[GenerateTypedNameReferences]
public sealed partial class StoreListingControl : Control
{
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IGameTiming _timing = default!;
    private readonly ClientGameTicker _ticker;

    private readonly ListingDataWithCostModifiers _data;

    private readonly bool _hasBalance;
    private readonly string _price;
    private readonly string _discount;
    public StoreListingControl(ListingDataWithCostModifiers data, string price, string discount, bool hasBalance, Texture? texture = null)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _ticker = _entity.System<ClientGameTicker>();

        _data = data;
        _hasBalance = hasBalance;
        _price = price;
        _discount = discount;

        StoreItemName.Text = ListingLocalisationHelpers.GetLocalisedNameOrEntityName(_data, _prototype);
        //rayten-start
        var contrSys = _entity.System<ContrabandSystem>();
        FormattedMessage description = new();
        description.AddText(ListingLocalisationHelpers.GetLocalisedDescriptionOrEntityDescription(_data, _prototype));
        description.PushNewline();
        if (_data.ProductEntity != null && _prototype.TryIndex<EntityPrototype>(_data.ProductEntity, out var proto))
        {
            if (proto.TryGetComponent<ContrabandComponent>(out var component)
                && _prototype.TryIndex<ContrabandSeverityPrototype>(component.Severity, out var severity))
            {
                description.AddMarkupPermissive(Loc.GetString(severity.ExamineText));
                if (severity.ShowDepartmentsAndJobs)
                {
                    description.PushNewline();
                    description.AddMarkupPermissive(contrSys.GenerateDepartmentExamineMessage(
                        component.AllowedDepartments,
                        component.AllowedJobs,
                        severity.Color,
                        ContrabandItemType.Item
                    ));
                }
            }
            else
            {
                description.AddMarkupPermissive(Loc.GetString("contraband-examine-text-in-the-clear"));
            }
        }
        StoreItemDescription.SetMessage(description);
        //rayten-end
        UpdateBuyButtonText();
        StoreItemBuyButton.Disabled = !CanBuy();

        StoreItemTexture.Texture = texture;
    }

    private bool CanBuy()
    {
        if (!_hasBalance)
            return false;

        var stationTime = _timing.CurTime.Subtract(_ticker.RoundStartTimeSpan);
        if (_data.RestockTime > stationTime)
            return false;

        return true;
    }

    private void UpdateBuyButtonText()
    {
        var stationTime = _timing.CurTime.Subtract(_ticker.RoundStartTimeSpan);
        if (_data.RestockTime > stationTime)
        {
            var timeLeftToBuy = stationTime - _data.RestockTime;
            StoreItemBuyButton.Text = timeLeftToBuy.Duration().ToString(@"mm\:ss");
        }
        else
        {
            DiscountSubText.Text = _discount;
            StoreItemBuyButton.Text = _price;
        }
    }

    private void UpdateName()
    {
        var name = ListingLocalisationHelpers.GetLocalisedNameOrEntityName(_data, _prototype);

        var stationTime = _timing.CurTime.Subtract(_ticker.RoundStartTimeSpan);
        if (_data.RestockTime > stationTime)
        {
            name += Loc.GetString("store-ui-button-out-of-stock");
        }

        StoreItemName.Text = name;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        UpdateBuyButtonText();
        UpdateName();
        StoreItemBuyButton.Disabled = !CanBuy();
    }
}
